---
final_name: redis-example-service-adapter
blobstore:
  provider: s3
  options:
    bucket_name: odb-releases
    folder_name: redis-example-service-adapter-release-bosh-blobs
    region: us-west-1
